HoldingERP.WebUI/Controllers/DepartmanController.cs
using HoldingERP.Business.Abstract;
using HoldingERP.Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HoldingERP.WebUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DepartmanController : Controller
    {
        private readonly IDepartmanService _departmanService;

        public DepartmanController(IDepartmanService departmanService)
        {
            _departmanService = departmanService;
        }

        public IActionResult Index()
        {
            
            var departmanlar = _departmanService.GetAll().ToList();
            return View(departmanlar);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Departman departman)
        {
            if (ModelState.IsValid)
            {
                _departmanService.Create(departman);
                _departmanService.SaveChanges();
                TempData["SuccessMessage"] = "Yeni departman başarıyla eklendi.";
                return RedirectToAction(nameof(Index));
            }
            return View(departman);
        }

        public IActionResult Edit(int id)
        {
            var departman = _departmanService.GetById(id);
            if (departman == null)
            {
                return NotFound();
            }
            return View(departman);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Departman departman)
        {
            if (id != departman.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _departmanService.Update(departman);
                    _departmanService.SaveChanges();
                    TempData["SuccessMessage"] = "Departman başarıyla güncellendi.";
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(departman);
        }

        public IActionResult Delete(int id)
        {
            var departman = _departmanService.GetById(id);
            if (departman == null)
            {
                return NotFound();
            }
            return View(departman);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var departman = _departmanService.GetById(id);
            if (departman != null)
            {
                _departmanService.Delete(departman);
                _departmanService.SaveChanges();
                TempData["SuccessMessage"] = "Departman başarıyla silindi.";
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

HoldingERP.WebUI/Controllers/OnayController.cs
using HoldingERP.Business.Abstract;
using HoldingERP.Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using static HoldingERP.Entities.Concrete.Teklif;

namespace HoldingERP.WebUI.Controllers
{
    [Authorize(Roles = "Admin, Onaycı")]
    public class OnayController : Controller
    {
        private readonly ITalepService _talepService;
        private readonly ITeklifService _teklifService;
        private readonly UserManager<Kullanici> _userManager;

        public OnayController(
            ITalepService talepService,
            ITeklifService teklifService,
            UserManager<Kullanici> userManager)
        {
            _talepService = talepService;
            _teklifService = teklifService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var astlarinIdleri = await _userManager.Users
                                                   .Where(u => u.AmirId == currentUser.Id)
                                                   .Select(u => u.Id)
                                                   .ToListAsync();

            var sorgu = _talepService.GetAll()
                .Include(t => t.TalepEdenKullanici)
                .ThenInclude(k => k.Departman);

            var isAdmin = await _userManager.IsInRoleAsync(currentUser, "Admin");

            IQueryable<SatinAlmaTalebi> filtrelenmisSorgu;

            if (isAdmin)
            {
                filtrelenmisSorgu = sorgu.Where(t => t.Durum == TalepDurumu.AmirOnayiBekliyor ||
                                                     t.Durum == TalepDurumu.GenelMudurOnayiBekliyor || 
                                                     t.Durum == TalepDurumu.YonetimKuruluOnayiBekliyor || 
                                                     t.Durum == TalepDurumu.MuhasebeMüdürüOnayiBekliyor); 
            }
            else 
            {
                filtrelenmisSorgu = sorgu.Where(t =>
                    (t.Durum == TalepDurumu.AmirOnayiBekliyor && astlarinIdleri.Contains(t.TalepEdenKullaniciId)) ||
                    t.Durum == TalepDurumu.GenelMudurOnayiBekliyor || 
                    t.Durum == TalepDurumu.YonetimKuruluOnayiBekliyor || 
                    t.Durum == TalepDurumu.MuhasebeMüdürüOnayiBekliyor 
                );
            }

            var onayBekleyenTalepler = await filtrelenmisSorgu.ToListAsync();
            return View(onayBekleyenTalepler);
        }

        public IActionResult Details(int id)
        {
            var talep = _talepService.GetAll()
                .Include(t => t.TalepEdenKullanici).ThenInclude(k => k.Departman)
                .Include(t => t.TalepUrunleri).ThenInclude(tu => tu.Urun)
                .FirstOrDefault(t => t.Id == id);

            if (talep == null) return NotFound();

            return View(talep);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Reject(int talepId)
        {
            var talep = _talepService.GetById(talepId);
            if (talep == null) return NotFound();

            talep.Durum = TalepDurumu.Reddedildi;
            _talepService.Update(talep);
            _talepService.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Approve(int talepId)
        {
            var talep = _talepService.GetById(talepId);
            if (talep == null) return NotFound();

            switch (talep.Durum)
            {
                case TalepDurumu.AmirOnayiBekliyor:
                    talep.Durum = TalepDurumu.SatınAlmada;
                    break;
                case TalepDurumu.GenelMudurOnayiBekliyor:
                case TalepDurumu.YonetimKuruluOnayiBekliyor:
                    talep.Durum = TalepDurumu.MuhasebeSürecinde; 
                    break;
                case TalepDurumu.MuhasebeMüdürüOnayiBekliyor:
                    var secilenTeklif = _teklifService.Get(t => t.SatinAlmaTalebiId == talepId && t.Durum == TeklifDurumu.Onaylandi); 

                    if (secilenTeklif != null)
                    {
                        secilenTeklif.Durum = TeklifDurumu.FaturaKesildi;
                        _teklifService.Update(secilenTeklif);
                    }

                    talep.Durum = TalepDurumu.FaturaKesildi;
                    break;
            }

            _talepService.Update(talep);
            _talepService.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

HoldingERP.WebUI/Controllers/StokController.cs
using HoldingERP.Business.Abstract;
using HoldingERP.Entities.Concrete;
using HoldingERP.WebUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using static HoldingERP.Entities.Concrete.Teklif;

namespace HoldingERP.WebUI.Controllers
{
    [Authorize(Roles = "Admin, Depo")]
    public class StokController : Controller
    {
        private readonly IStokService _stokService;
        private readonly IDepartmanService _departmanService; 
        private readonly IStokHareketiService _stokHareketiService; 
        private readonly UserManager<Kullanici> _userManager;
        private readonly ITalepService _talepService;
        private readonly ITeklifService _teklifService;
        private readonly IFaturaService _faturaService;
        

        public StokController(IStokService stokService, IDepartmanService departmanService, IStokHareketiService stokHareketiService, UserManager<Kullanici> userManager, ITalepService talepService, ITeklifService teklifService, IFaturaService faturaService) 
        {
            _stokService = stokService;
            _departmanService = departmanService;
            _stokHareketiService = stokHareketiService;
            _userManager = userManager;
            _talepService = talepService;
            _teklifService = teklifService;
            _faturaService = faturaService;
        }

        public IActionResult Index()
        {
            var stokListesi = _stokService.GetAll()
                                          .Include(s => s.Urun)
                                          .ToList();
            return View(stokListesi);
        }

        public IActionResult StokCikis(int id)
        {
            var stok = _stokService.GetAll().Include(s => s.Urun).FirstOrDefault(s => s.Id == id);
            if (stok == null) return NotFound();

            var model = new StokCikisViewModel
            {
                StokId = stok.Id,
                UrunAdi = stok.Urun.Ad,
                MevcutMiktar = stok.Miktar,
                Departmanlar = _departmanService.GetAll().ToList()
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> StokCikis(StokCikisViewModel model)
        {
            if (ModelState.IsValid)
            {
                var stok = _stokService.GetById(model.StokId);
                if (stok == null) return NotFound();

                if (model.CikisMiktari > stok.Miktar)
                {
                    ModelState.AddModelError("CikisMiktari", "Çıkış miktarı mevcut stoktan fazla olamaz.");
                    model.Departmanlar = _departmanService.GetAll().ToList(); 
                    return View(model);
                }

                var currentUser = await _userManager.GetUserAsync(User);

                stok.Miktar -= model.CikisMiktari;
                stok.GuncellemeTarihi = DateTime.Now;
                _stokService.Update(stok);

                var hareket = new StokHareketi
                {
                    UrunId = stok.UrunId,
                    Miktar = -model.CikisMiktari, 
                    IslemTuru = IslemTuru.Cikis,
                    Tarih = DateTime.Now,
                    IslemiYapanKullaniciId = currentUser.Id,
                };
                _stokHareketiService.Create(hareket);
                _stokService.SaveChanges();

                TempData["SuccessMessage"] = $"{model.CikisMiktari} adet {model.UrunAdi} stoktan başarıyla düşüldü.";
                return RedirectToAction("Index");
            }
            model.Departmanlar = _departmanService.GetAll().ToList();
            return View(model);
        }

        public IActionResult StokGirisBekleyenler()
        {
            var girisBekleyenTalepler = _talepService.GetAll()
                .Include(t => t.TalepEdenKullanici.Departman)
                .Where(t => t.Durum == TalepDurumu.FaturaKesildi)
                .ToList();

            return View(girisBekleyenTalepler);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> StokGirisiYap(int talepId)
        {
            var anaTalep = _talepService.GetById(talepId);
            if (anaTalep == null || anaTalep.Durum != TalepDurumu.FaturaKesildi)
            {
                return RedirectToAction(nameof(StokGirisBekleyenler));
            }

            var onaylanmisTeklif = _teklifService.GetAll() 
                                            .Include(t => t.TeklifKalemleri)
                                            .FirstOrDefault(t => t.SatinAlmaTalebiId == talepId && t.Durum == TeklifDurumu.FaturaKesildi);

            if (onaylanmisTeklif == null) { }

            var currentUser = await _userManager.GetUserAsync(User);
            var fatura = _faturaService.Get(f => f.TeklifId == onaylanmisTeklif.Id); 

            _stokService.FaturaIleStokGirisiYap(fatura, onaylanmisTeklif.TeklifKalemleri, talepId, currentUser.Id);

            anaTalep.Durum = TalepDurumu.StoktaMevcut;
            _talepService.Update(anaTalep);

            _talepService.SaveChanges();

            TempData["SuccessMessage"] = "Ürünler stoğa başarıyla eklendi.";
            return RedirectToAction(nameof(StokGirisBekleyenler));
        }

    }
}

HoldingERP.WebUI/Views/Shared/_Layout_eski.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ahlatçı Holding ERP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/HoldingERP.WebUI.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HoldingERP.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <ul class="navbar-nav">
                        @if (User.Identity != null && User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                            </li>

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Departman" asp-action="Index">Departman Yönetimi</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="KullaniciYonetimi" asp-action="Index">Kullanıcı Yönetimi</a>
                                </li>
                            }

                            @if (User.IsInRole("Admin") || User.IsInRole("Talep Eden"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="SatinAlmaTalebi" asp-action="Index">Taleplerim</a>
                                </li>
                            }

                            @if (User.IsInRole("Admin") || User.IsInRole("Onaycı"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Onay" asp-action="Index">Onay İşlemleri</a>
                                </li>
                            }

                            @if (User.IsInRole("Admin") || User.IsInRole("Muhasebe"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Muhasebe" asp-action="Index">Muhasebe</a>
                                </li>
                            }

                            @if (User.IsInRole("Admin") || User.IsInRole("Satın Almacı"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownSatinAlma" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Satın Alma
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownSatinAlma">
                                        <li><a class="dropdown-item" asp-controller="SatinAlma" asp-action="Index">Yeni Talepler</a></li>
                                        <li><a class="dropdown-item" asp-controller="SatinAlma" asp-action="TeklifleriDegerlendirListesi">Teklif Değerlendirme</a></li>
                                    </ul>
                                </li>
                            }

                            @if (User.IsInRole("Admin") || User.IsInRole("Depo"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Stok" asp-action="Index">Stok Yönetimi</a>
                                </li>
                            }

                        }
                        
                    </ul>

                    <div class="navbar-nav d-flex flex-row align-items-center">
                        @if (User.Identity != null && User.Identity.IsAuthenticated)
                        {
                            @await Component.InvokeAsync("Notification")

                            <li class="nav-item">
                                <a class="nav-link text-dark" title="Manage">Merhaba @User.Identity.Name!</a>
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" asp-controller="Account" asp-action="Logout" method="post">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Çıkış Yap</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Giriş Yap</a>
                            </li>
                        }
                    </div>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Holding ERP
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>